name: Formatting python code
on:
  push:
    paths:
    - '**.py'
jobs:
  autoyapf:
    runs-on: ubuntu-latest
    steps:
      - name: Install dev dependencies
        run: pip install -r requirements.txt & pip install flake8
      
      - name: Link with flake8
        run: flake8 .
